language: python
python:
  - '2.7'
env:
  - TOXENV=py27-pyramid13
  - TOXENV=py27-pyramid14
  - TOXENV=py27-pyramid15
# command to install dependencies
install: 
  - 'easy_install -U setuptools'
  - 'pip install -U pip'
  - 'pip install tox'
# command to run tests
script: 
  - 'tox'
  - 'pip install flake8'
  - 'flake8 pyramid_handy --ignore=E501,W293'
